#!/bin/sh
# Copyright(c) 2011 Red Hat, Inc.
#
# This is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library in the file COPYING.LIB;
# if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA
#
# @author Mladen Turk
#
# Master build task
#

procfiles()
{
    for o
    do
        case $o in
            .  )
               echo .
               break
            ;;
            /* )
                echo .$o
            ;;
            *  )
                echo $o
            ;;
        esac
    done
}

genbuildspec()
{
    test ".$2" = . && $2=.
    cat > "$2/BUILDSPEC" <<EOH
Name: $1
Summary: $summary
Group: $group
Version: $version
Release: $release
Platform: $_os
Architecture: $_arch
License: $license
URL: $origin
Build-By: $__ccver
Timestamp: `date -R`
Changelog:
`changelog 1`
EOH

}

# Execute hooks
build_prepare()
{
    $ECHO "build prepare \`$_source.$_arch'"
    test -d "$_sourcedir/$_source" || xbexit 1 "cannot find \`$_source' directory"
    copypdir "$_sourcedir/$_source" "$_builddir/$_source.$_arch"
    install -m 755 -d "$buildroot"
    (
        cd "$_builddir/$_source.$_arch"
        for i in $name.${_os_c}prep $name.buildprep
        do
            if [ -s "$_packagedir/$i" ]
            then
                . "$_packagedir/$i"
                break
            fi
        done
        return 0
    )
    test $? -ne 0 && exit 1
    return 0
}

build_execute()
{
    files=
    files_doc=
    files_devel=
    files_devel_doc=
    $ECHO "build execute \`$_source.$_arch'"
    (
       cd "$_builddir/$_source.$_arch"
       for i in $name.${_os_c}build $name.build
       do
            if [ -s "$_packagedir/$i" ]
            then
                files=.
                . "$_packagedir/$i"
                break
            fi
        done
        cd "$buildroot"
        if [ ".$files" != . ]
        then
            a="`procfiles $files`"
            if [ ".$files_doc" != . ]
            then
                d="$_docdir/$name-$version"
                newdir "$buildroot$d"
                for i in $files_doc
                do
                    case $i in
                        @BUILDSPEC )
                            i=BUILDSPEC
                            genbuildspec $name "$buildroot$d"
                        ;;
                        @*         )
                            copydir $_builddir/$_source.$_arch/$i "$buildroot$d/$i"
                            i=`basename "$i"`
                        ;;
                        *          )
                            cp -f $_builddir/$_source.$_arch/$i "$buildroot$d/"
                            i=`basename "$i"`
                        ;;
                    esac
                    a="`procfiles $a $d/$i`"
                done
            fi
            fixzipperms
            $ECHO "Creating $_destdir/$name-$version-$release.$_arch.zip"
            zip -r9 "$_destdir/$name-$version-$release.$_arch.zip" $a
            test $? -ne 0 && exit 1
        fi
        if [ ".$files_devel" != . ]
        then
            a="`procfiles $files_devel`"
            if [ ".$files_devel_doc" != . ]
            then
                d="$_docdir/$name-devel-$version"
                newdir "$buildroot$d"
                for i in $files_devel_doc
                do
                    case $i in
                        @BUILDSPEC )
                            i=BUILDSPEC
                            genbuildspec $name "$buildroot$d"
                        ;;
                        @*         )
                            copydir $_builddir/$_source.$_arch/$i "$buildroot$d/$i"
                            i=`basename "$i"`
                        ;;
                        *          )
                            cp -f $_builddir/$_source.$_arch/$i "$buildroot$d/"
                            i=`basename "$i"`
                        ;;
                    esac
                    a="`procfiles $a $d/$i`"
                done
            fi
            fixzipperms
            $ECHO "Creating $_destdir/$name-devel-$version-$release.$_arch.zip"
            zip -r9 "$_destdir/$name-devel-$version-$release.$_arch.zip" $a
        fi
        return 0
    )
    return $?
}
