#!/bin/sh
# Copyright(c) 2011 Red Hat, Inc.
#
# This is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library in the file COPYING.LIB;
# if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA
#
# @author Mladen Turk
#
#
check_prepare()
{
    $INFO "Check task started"
    echo "Dumping environment ..."
    return 0
}

check_execute()
{
    cat << EOH
XBuild:
program         $xb_prognam
version         $XB_VERSION
root            $xb_dirname

Specfile definitions:
name            $name
specfile        $specfile
release         $release
dist            $dist

Host info:
_os             $_os
_arch           $_arch
__isa_bits      $__isa_bits
__isa_name      $__isa_name
__isa           $__isa
_host_cpu       $_host_cpu
_host_os        $_host_os
_host           $_host

Tools:
__awk           $__awk
__tar           $__tar
__gzip          $__gzip
__bzip2         $__bzip2
__xz            $__xz

Build:
_bin            $_bin
_lib            $_lib
_sbin           $_sbin

Environment:
__cwd           $__cwd
__tag_name      $__tag_name

hostname        `hostname`
PATH            $PATH

EOH
if [ "$_os" = windows ]; then
    cat << EOH
Windows envronment:
WINUEXECC cmd.exe /C set

EOH
fi
    return 0
}

check_cleanup()
{
    $INFO "Check task finsihed"
    return 0
}

