#!/bin/sh
# Copyright(c) 2011 Red Hat, Inc.
#
# This is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library in the file COPYING.LIB;
# if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA
#
# @author Mladen Turk
#
# Handles build dependencies
#


# Execute hooks
depends_prepare()
{
    $ECHO "depends prepare"
    if $_rootdir != / ]
    then
        newdir "$_rootdir"
    fi
    return 0
}

depends_execute()
{
    $ECHO "depends execute"
    (
        cd "$_rootdir"
        echo "Finding .zip file dependencies in $_buildreqsdir"
        IFS=$__lf
        d="`find "$_buildreqsdir" -name '*.'$_arch'.zip' -type f 2>/dev/null`"
        for i in $d
        do
            IFS=$__ifs
            case "$i" in
                *xbuild-*  )
                    echo "Skipping inherent xbuild dependency"
                    continue
                ;;
                *.$_arch.* )
                    echo "Found zip archive: \`$i"
                ;;                
            esac
        done
        echo "Finding .tgz file dependencies"
        d="`find . -name '*.'$_arch'.tar.*' -type f`"
        for i in $d
        do
            IFS=$__ifs
            case "$i" in
                *.gz  )
                    echo "Found tar.gz archive \`$i'"
                ;;
                *.bz2 )
                    echo "Found tar.bz2 archive \`$i'"
                ;;
            esac
        done
        echo "Finding .rpm file dependencies"
        d="`find . -name '*.rpm' -type f`"
        for i in $d
        do
            IFS=$__ifs
            case "$i" in
                *.$_arch.*  )
                    echo "Found rpm archive \`$i'"
                ;;
                *.noarch.*  )
                    echo "Found noarch rpm archive \`$i'"
                ;;
            esac
        done
    )
}

