#!/bin/sh
# Copyright(c) 2011 Red Hat, Inc.
#
# This is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library in the file COPYING.LIB;
# if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA
#
# @author Mladen Turk
#
# Handles install task for creating
# platform specific packages
#

# Execute hooks
dist_prepare()
{
    $ECHO "dist prepare \`$_source.$_arch'"
    test -d "$_sourcedir/$_source" || xbexit 1 "cannot find \`$_source' directory"
    return 0
}

dist_execute()
{
    $ECHO "dist execute"
    (
        files=
        cd "$_builddir/$_source.$_arch"
        for i in $name.${_os_c}dist $name.install
        do
            if [ -s "$_sourcedir/$i" ]
            then
                . "$_sourcedir/$i"
                break
            fi
        done
        cd "$buildroot"
        if [ ".$files" != . ]
        then
            cp -f $files "$_outputdir"
        fi
        return 0
    )
    return $?
}
