#!/bin/sh
# Copyright(c) 2011 Red Hat, Inc.
#
# This is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library in the file COPYING.LIB;
# if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA
#
# @author Mladen Turk
#
# Publish artifacts to repository
#
_sharedroot="/home/shared"
_publishroot=""
# Execute hooks
publish_prepare()
{
    $ECHO "publish prepare \`$_source.$_arch'"    
    test -d "$_sharedroot" || _sharedroot="/export/home/shared"
    _publishroot="$_sharedroot/xbuildroot/packages"
    mkdir -p "$_publishroot"
    return $?
}

publish_execute()
{
    $ECHO "publish execute"
    (
        d="$_publishroot/$name/$version/$release/$_arch"
        mkdir -p "$d"
        for i in $NVR.*
        do
            if [ -f "$d/$i" ]; then
                if [ ".$has_force" = .no ]; then
                    $ECHO "$i already present in \`$d'"
                    $ECHO "use --force to override."
                    continue
                fi
            fi
            cp $i "$d/"
            echo "$version $release $_arch" >> "$_publishroot/$name/.${_os_c}repo"
        done
        for i in $NDVR.*
        do
            if [ -f "$d/$i" ]; then
                if [ ".$has_force" = .no ]; then
                    $ECHO "$i already present in \`$d'"
                    continue
                fi
            fi
            cp $i "$d/"
        done
        
    )
    return $?    
}
