#!/bin/sh
# Copyright(c) 2011 Red Hat, Inc.
#
# This is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library in the file COPYING.LIB;
# if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA
#
# @author Mladen Turk
#
# This is the configuration file to treate the CA certificate of the
# _DEMONSTRATION ONLY_ 'Tequila' Certificate Authority.
# This CA is used to sign the localhost.crt and user.crt
# because self-signed server certificates are not accepted by all browsers.
# NEVER USE THIS CA YOURSELF FOR REAL LIFE! INSTEAD EITHER USE A PUBLICALLY
# KNOWN CA OR CREATE YOUR OWN CA!
#
# Downloads entries from sources file
# in the current directory and uncopresses them to the
# RPM_SOURCE_DIR.
#
# Added:
# If Source points to directoy this dircetory is copied
# recursively to the source directory.
#

downloadsources()
{
    test -s sources || return 0
    IFS=$__lf
    s=`cat sources 2>/dev/null`
    for i in $s
    do
        IFS=$__ifs
        h=`echo $i | $__awk '{print $1}'`
        p=`echo $i | $__awk '{print $2}'`
        u=http://cvs.devel.redhat.com/repo/dist/$name/$p/$h/$p
        if [ ! -e "$p" ]
        then
            $ECHO "Getting: \`$u'"
            wget --tries=0 --quiet $u
            test $? -ne 0 && xbexit 1 "failed to download redhat module \`$u'"
        fi
        case "$p" in
            *.tar.gz|*.tgz )
                d=$__gzip
            ;;
            *.tar.bz2 )
                d=$__bzip2
            ;;
            *.tar.lzma|*.xz )
                d=$__xz
            ;;
            * )
                xbexit 1 "cannot determine compression algorithm for \`$p'"
            ;;
        esac
        test ".$has_verbose" = .yes && v=-xvvf || v=-xf
        $ECHO "$d -cd "$p" | $__tar $v -"
        (
            cd "$_sourcedir"
            $d -cd "$_destdir/$p" | $__tar $v -
        )
        test $? -ne 0 && xbexit 1 "failed to uncompress \`$p'"
    done
    return 0
}

copysources()
{
    test ".$has_verbose" = .yes && c=vf || c=f
    IFS=$__lf
    s=`$__grep -i '^Source[0-9]*:' $specfile | $__sed 's/\w*:[[:blank:]]*//'`
    for i in $s
    do
        IFS=$__ifs
        case "$i" in
             *%{* ) e="`speceval $i`" ;;
             *    ) e="$i" ;;
        esac
        d="`dirname $e`"
        b="`basename $e`"
        test -e "$b" || continue
        case "$d" in
            http*://* )
                d=.
            ;;
        esac
        if [ -d "$b" ]
        then
            test "$d"  = . && d=""
            cp -R$c "$b" "$_sourcedir/$d" 2>/dev/null
        else
            test "$d" != . && mkdir -p "$_sourcedir/$d" 2>/dev/null
            test "$d"  = . && d=""
            cp -$c "$b" "$_sourcedir/$d" 2>/dev/null
        fi
    done
}

applypatches()
{

    IFS=$__lf
    c=`grep -i '^patch[0-9]*:' $specfile`
    for i in $c
    do
        IFS=$__ifs
        p=`echo "$i" | $__sed 's/[pP]atch\([0-9]*\).*/\1/'`
        v=`echo "$i" | $__sed 's/\w*:[[:blank:]]*//'`
        r=`$__grep -i '^%patch'$p' ' $specfile | $__sed 's/%\w*[[:blank:]]*//'`
        if [ ".$r" != "." ]
        then
            case "$r" in
                -* )
                    r="`echo $r | sed 's/\(.*\)\(\..*\)/\1 -z \2/'`"
                    test ".$has_verbose" = .no && r="-s $r"
                ;;
            esac
            case "$v" in
                http*://* )
                    v=`basename "$v"`
                ;;
            esac
            (
                cd "$_sourcedir/$_source"
                case "$r" in
                    -*  )
                        if [ -s "$RPM_ROOT_DIR/$v" ]
                        then
                            patch $r < "$RPM_ROOT_DIR/$v"
                        else
                            $ECHO "missing patch: \`$v'"
                        fi
                    ;;
                    *   )
                        eval "$r $v"
                    ;;
                esac
            )
        fi
    done
}

# Execute hooks
sources_prepare()
{
    $ECHO "Preparing sources task"

    rm -rf "$_sourcedir/$_source" >/dev/null 2>&1
    if [ -s sources ]
    then
        makedir "$_sourcedir"
    else
        makedir "$_sourcedir/$_source"
    fi
    return 0
}

sources_execute()
{
    $ECHO "Executing sources task"
    (
        downloadsources
    )
    test -d "$_sourcedir/$_source" || xbexit 1 "cannot find \`$_source' directory"
    (
        applypatches
    )
    (
        copysources
    )        
    return 0
}

sources_cleanup()
{
    return 0
}
