#!/bin/sh
# Copyright(c) 2011 Red Hat, Inc.
#
# This is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library in the file COPYING.LIB;
# if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA
#
# @author Mladen Turk
#
# Contains all default variables
#

XB_VERSION=2.0.1
ECHO=:
# String constants
__tab="	"
__lf="
"
__ifs=$IFS
has_maintainer_mode=no
has_buildspec=no
has_verbose=no
has_force=no
buildrequires=
requires=
dist=
name=
version="$version"
release="$release"
_prefix=
_bindir=
_libdir=
_sbindir=
_includedir=
_datadir=
_docdir=
_mandir=
_os=
_os_c=
_os_r=
_arch=
__isa=
__isa_bits=
__isa_name=
_host=
_host_os=
_host_cpu=
__year=`date +%Y`
__month=`date +%m`
__mday=`date +%d`
__cwd="`pwd`"
__tag_name=`basename "$__cwd"`
o="`uname -s | tr '[A-Z]' '[a-z]' | sed 's/[^[:alnum:]].*//'`"
case ".$o" in
    .cygwin ) include stddefs.windows ;;
    .sunos  ) include stddefs.solaris ;;
    *       ) include stddefs.$o      ;;
esac
specfile="`find . -maxdepth 1 -name '*.spec' -type f -exec basename '{}' \;`"
ix86="i386 i486 i586 i686 pentium3 pentium4 athlon geode"
